### ISSUE TITLE
feat: Manual Token Refrsh

### ISSUE THREAD

**Issue by t-unit** [Bdaya-Dev/oidc#23]
**Description**

I could not find a way to manually trigger token refreshes. Automatic refresh is great, but sometimes we need the ability to perform is manually.

**Requirements**

- make API public that allow refreshing tokens

**Additional Context**

Sometimes devices don't have the correct time and date set. Due to that, we rely performing a token refresh after a corresponding error response from our backend to not require a manual login all the time.

**Comment by ahmednfwela** [comment]
I see, this should be easy to implement so I will add it soon™

**Comment by ahmednfwela** [comment]
@t-unit created PR #24

**Comment by t-unit** [comment]
@ahmednfwela thanks a lot for the quick implementation!

**Comment by ahmednfwela** [comment]
You are welcome! consider dropping a star on github and pub.dev if you like the package 😄
