### ISSUE TITLE
Example uses bad practice with global state

### ISSUE THREAD

**Issue by friesoft** [Bdaya-Dev/oidc#39]
I would really appreciate if the example would be using good practices as opposed to the currently stated bad practice using a global state. I'm pretty new to flutter and I'm having trouble adapting the example to use a dependency injection framework.
If easily possible it would be great if the example could show how to do this properly.

https://github.com/Bdaya-Dev/oidc/blob/8c068e2aca2e66d0db2cb11c86490ece01b6f409/packages/oidc/example/lib/app_state.dart#L12

**Comment by ahmednfwela** [comment]
sure, what state management do you want to use?

**Comment by friesoft** [comment]
How about get_it? But I'm fine with any, as I'm pretty new to flutter and don't know yet which one is better

**Comment by danielRi** [comment]
Is it really bad practice? It uses SharedValue, also in e.G. Riverpod, everything is a global variable. get_it is not really a state management package, its just for dependency injection/service locator.

**Comment by ahmednfwela** [comment]
I agree with @danielRi , managing state is outside the scope of this package and it depends on which stack you use.

please let me know @friesoft if you need further assistance.
