### ISSUE TITLE
fix: The library doesn't keep the user logged in overnight

### ISSUE THREAD

**Issue by NiallBunting** [Bdaya-Dev/oidc#47]
**Description**

Every morning I need to log back into the app. I'm using offline refresh tokens that have an expiry of 200 days.

**Steps To Reproduce**

Leave the app in the background overnight. When I open it in the morning the user has logged out.

**Expected Behavior**

Since the refresh token is set for 200 days they should remain logged in.

**Additional Context**

This is my setup:

```
init(String deviceId) async {
    _manager = OidcUserManager.lazy(
      discoveryDocumentUri: OidcUtils.getOpenIdConfigWellKnownUri(
        Uri.parse(ApiConstants.keycloakURL),
      ),
      clientCredentials: OidcClientAuthentication.none(clientId: ApiConstants.keycloakClient),
      store: OidcDefaultStore(),
      settings: OidcUserManagerSettings(
        extraAuthenticationParameters: {},
        // DO NOT CHANGE THE ORDER deviceId RELIES UPON THE DEVICE BEING LAST
        scope: ['openid', 'profile', 'email', 'offline_access', 'urn:matrix:org.matrix.msc2967.client:device:${deviceId}'
        ],
        redirectUri: Uri.parse('${ApiConstants.appId}:/oauth2redirect'),
        postLogoutRedirectUri: Uri.parse('${ApiConstants.appId}:/endsessionredirect'),
      ),
    );

    _manager.userChanges().listen((user) async {
      print('currentUser changed to: ${user}');
      notifyListeners();
    });

    await _manager.init();
  }
  ```

**Comment by ahmednfwela** [comment]
when calling init the package tries to exchange a token using the stored refresh token, if it fails it logs out silently.

so next time try opening the network tab in your browser (f12 in Google chrome) to monitor outgoing requests and see what the problem is.

**Comment by NiallBunting** [comment]
Hi, my Keycloak server doesn't receive any requests trying to authenticate. It only receives requests asking for it's openid-conf and certs.

**Comment by ahmednfwela** [comment]
I see, I will have to check to see why

**Comment by NiallBunting** [comment]
I don't know if this helps but I have noticed that the library sometimes updates the user as null before getting the token on start up. So the first event can be null before getting an actual user. So in my routing i've had to do:
```
  if(user == null) {
    navigateToLogin();
  } else {
    if(userIsOnLogin() {
      navigateToMain();
    }
    return null;
  }
```
Rather than the simpler:
```
  if(user == null) {
    navigateToLogin();
  }
  return null;
```
It would be handy if it did have creds installed it would try them before sending the null user event on init.

**Comment by NiallBunting** [comment]
I have managed to hack this to work with the following code:

```
   _manager.userChanges().listen((user) async {

      if (user != null) {
        final dir = await getApplicationSupportDirectory();
        var box = await Hive.openBox('tokenBox', path: dir.path);
        box.put('token', user.token.refreshToken);
      } else {
        print("Using hive token");
        final dir = await getApplicationSupportDirectory();
        var box = await Hive.openBox('tokenBok', path: dir.path);
        String? token = box.get('token');
        if(token != null && _manager.didInit) {
          print("Refreshing token");
          _manager.refreshToken(overrideRefreshToken: token);
        }
      }

      print('currentUser changed to: ${user}');
      notifyListeners();
    });
```

```
/// Refreshes the token manually.
  ///
  /// If token can't be refreshed `null` will be returned.
  ///
  /// Token can be refreshed in the following cases:
  /// 1. grant_types_supported MUST include refresh_token
  /// 2. the [currentUser] MUST NOT be null
  /// 3. the `currentUser.token` MUST include refreshToken
  ///
  /// If any of these conditions are not met, null is returned.
  ///
  /// An [OidcException] will be thrown if the server returns an error.
  Future<OidcUser?> refreshToken({String? overrideRefreshToken}) async {
    if (!discoveryDocument.grantTypesSupportedOrDefault
        .contains(OidcConstants_GrantType.refreshToken)) {
      //Server doesn't support refresh_token grant.
      return null;
    }
    //final user = currentUser;
    //if (user == null) {
    //  return null;
    //}
    final refreshToken = overrideRefreshToken ?? currentUser?.token.refreshToken;
    if (refreshToken == null) {
      // Can't refresh the access token anyway.
      return null;
    }

    final tokenResponse = await OidcEndpoints.token(
      tokenEndpoint: discoveryDocument.tokenEndpoint!,
      credentials: clientCredentials,
      client: httpClient,
      headers: settings.extraTokenHeaders,
      request: OidcTokenRequest.refreshToken(
        refreshToken: refreshToken,
        clientId: clientCredentials.clientId,
        clientSecret: clientCredentials.clientSecret,
        extra: settings.extraTokenParameters,
        scope: settings.scope,
      ),
    );
    return _createUserFromToken(
      token: OidcToken.fromResponse(
        tokenResponse,
        overrideExpiresIn: settings.getExpiresIn?.call(tokenResponse),
        sessionState: currentUser?.token.sessionState,
      ),
      nonce: null,
      attributes: null,
    );
  }
```

**Comment by ahmednfwela** [comment]
> I don't know if this helps but I have noticed that the library sometimes updates the user as null before getting the token on start up. So the first event can be null before getting an actual user.

This is just a side effect of listening to the stream before calling `init`, this is why you should call `init` in your main or at least use a pattern similar to this:

https://github.com/Bdaya-Dev/oidc/blob/4e9fbaca58a0c86abcb592c77d06b38706b178b5/packages/oidc/example/lib/main.dart#L71-L90

this way you don't have to do weird magic in your routing

**Comment by chrisdrobison** [comment]
I'm seeing this issue as well. I am initing like you have in the examples, but it doesn't appear to attempt to do a refresh of the token, it just checks the expiration and fails.

**Comment by chrisdrobison** [comment]
I've been tracing through the code and it appears that when this library loads things from cache and it encounters an expired token, it just throws it away rather than attempting a refresh of the token if one is available.

**Comment by ahmednfwela** [comment]
I have also investigated this, the particular area that fails is this:

https://github.com/Bdaya-Dev/oidc/blob/9649ee0b856906cce2afd691d641191075090a43/packages/oidc/lib/src/managers/user_manager.dart#L796-L822

when an `id_token` is found to have expired (by checking the `exp` field), it's registered as an error, thus leading to the tokens being removed.

The solution here is to check for token expiration right after loading it here:
https://github.com/Bdaya-Dev/oidc/blob/9649ee0b856906cce2afd691d641191075090a43/packages/oidc/lib/src/managers/user_manager.dart#L939


will create a PR for it soon.

**Comment by MarinCouderc** [comment]
Can confirm having the same issue

**Comment by ahmednfwela** [comment]
Version [0.5.2](https://pub.dev/packages/oidc/changelog#052) has been released to address this issue.

Waiting for your feedback!
