### ISSUE TITLE
fix:  Missing idToken in ResourceOwnerPasswordValidation Grant Response causes Exception

### ISSUE THREAD

**Issue by emil-st** [Bdaya-Dev/oidc#62]
**Description**
 When using the ResourceOwnerPasswordValidation grant type with the _loginPassword_ method, an exception is thrown due to the absence of an idToken in the grant response. According to the OAuth 2.0 and OpenID Connect standards, the Resource Owner Password Credentials (ROPC) flow does not return an id_token. However, the library seems to expect this token, leading to an exception.

**Steps To Reproduce**

1. Call the loginPassword method with valid username and password arguments in OidcUserManager.
2. Observe that the method throws an OidcException when the idToken is null.

**Expected Behavior:**
The library should handle the absence of an idToken in the response for the ResourceOwnerPasswordValidation grant type, as this grant type does not inherently return an id_token.

**Actual Behavior:**
An exception is thrown due to the idToken being null, which is an expected behavior in the context of the ResourceOwnerPasswordValidation grant type.

**Comment by ahmednfwela** [comment]
Thanks for raising the issue, you are right, the OIDC spec doesn't include the resource owner password grant, it's only part of the [OAuth spec (RFC 6749)](https://datatracker.ietf.org/doc/html/rfc6749#section-4.3).

However the user manager NEEDS an `id_token` to be parsed as JWT and create the `OidcUser` object.

the OAuth spec only uses `access_token` which isn't necessarily a JWT.

A possible solution is to introduce a new customization field `String Function(OidcToken) getIdToken` that is provided by the user, where the user can enforce the `access_token` to be used as a JWT.

which one do you prefer @emil-st ?

**Comment by ahmednfwela** [comment]
Also if your Idp is public, can you send me its url for testing ?
