### ISSUE TITLE
fix: Automatic user logout with ClientSocketException when network is unavailable

### ISSUE THREAD

**Issue by heralight** [Bdaya-Dev/oidc#69]
**Description**

When the application is launched without a network connection, users are automatically logged out due to a ClientSocketException thrown in the _loadCachedTokens method.

**Steps To Reproduce**

1. Ensure the user is logged in with valid tokens stored in cache.
1. Disconnect the device from any network.
1. Close the app and launch it again (flutter restart).
2. The user is now disconnected after a ClientSocketException in _loadCachedTokens that call :
```dart
await store.removeMany(
        OidcStoreNamespace.secureTokens,
        keys: usedKeys,
      );
  ```

**Expected Behavior**

* The app should attempt to load the cached tokens without requiring a network connection. If the tokens are valid and not expired, the user should remain logged in, or the app should handle the situation gracefully if tokens need refreshing but no network is available.

same problem with the init function. If no network, the discovery failed.
* when not login in, the init function must call if no network on first attempt and failed to initialize before any login.

**Actual Behavior**

* The application throws a ClientSocketException and logs out the user when attempting to load cached tokens without a network connection.
* when not login in, the init function  failed if no network, when network is ok and the login failed too.

**Possible Solution Suggestion**
It would be beneficial to implement a check to see if the network is available before attempting operations that require a connection. Additionally, the token loading mechanism could handle exceptions more gracefully, perhaps by using cached tokens if they are still valid and postponing token refresh until a network connection is reestablished. Same for the init call.

Best regards,

Alexandre

**Comment by ahmednfwela** [comment]
I agree this is a problem especially for offline-first apps (desktop mainly), let me see what I can do 👍

**Comment by ahmednfwela** [comment]
hi @heralight , I have studied this issue in the past couple of days, and here is the result of my research:

The issue here is a matter of convenience vs security.

1. Support offline auth (convenient)
    1. The developer MUST opt into this behavior as it will have security concerns.
    2. Handle token validation
        a. The jose_plus package MUST be able to serialize and deserialize a resolved `JsonWebKeyStore`.
        b. OR enforce `strictJwtVerification = false` when offline support is desired.
    3. the app MUST allow expired access/id tokens to remain when refreshing has failed
2. Don't support offline auth (secure) (default)
    - User tokens will be removed if they can't be verified or refreshed.

to support offline auth, a new setting can be introduced in `OidcUserManagerSettings` (e.g. `OidcUserManagerSettings.supportOfflineAuth`) that's mutually exclusive with `strictJwtVerification` until we are able to cache JWK stores.

**Comment by ahmednfwela** [comment]
Update:

I have introduced offline support in pr #89 with support to caching JWKs

**Comment by heralight** [comment]
@ahmednfwela thank you for your feedback and work, 
as you said it's a matter between conveniency and security. But as it was, the plugin was nearly unusable due to this auto disconnection. 

ideally, in secure mode, the disconnection must only appears when the refresh AND and have internet, not on network error.
After that, the insecure mode has very low risk, due to the fact, that the token will reject by the server...

I will upgrade to your new version and test supportOfflineAuth.

best regards,

Alexandre
