### ISSUE TITLE
fix: OidcUserManager.logout not using default OidcPlatformSpecificOptions

### ISSUE THREAD

**Issue by kmcgill88** [Bdaya-Dev/oidc#72]
**Description**
I think this a simple oversight. When calling [logout](https://github.com/Bdaya-Dev/oidc/blob/main/packages/oidc/lib/src/managers/user_manager.dart#L339) a new instance of `OidcPlatformSpecificOptions` is instantiated, ignoring the default options passed from the `lazy` constructor. Instead, I think this should be `options ??= settings.options;`

I ran into this experimenting with iOS. In my use case, I want `preferEphemeralSession` to be used for log in and out. 

```dart
 options: const OidcPlatformSpecificOptions(
    ios: OidcPlatformSpecificOptions_AppAuth_IosMacos(
      preferEphemeralSession: true,
    ),
  ),
```

A simple workaround is to pass the same options on the managers settings like so 
```dart
  await manager.logout(
    options: manager.settings.options,
  );
```

**Expected Behavior**

I expect `OidcUserManagerSettings` and `OidcPlatformSpecificOptions` to be used for `loginAuthorizationCodeFlow` and `logout` by default without the need to override.

**Comment by ahmednfwela** [comment]
Yes you are right, this will be solved next release
