### ISSUE TITLE
 preferEphemeralSession for Android

### ISSUE THREAD

**Issue by josefwilhelm-innio** [Bdaya-Dev/oidc#76]
Is there a way to have something like `preferEphemeralSession` in Android?

Or a way to clear the cookies when calling loginAuthorizationCodeFlow()

**Comment by ahmednfwela** [comment]
Since we are using `flutter_appauth` upstream, which uses the android appauth SDK, [it's not possible](https://pub.dev/packages/flutter_appauth#ephemeral-sessions-ios-and-macos-only)

**Comment by ahmednfwela** [comment]
Related issue: https://github.com/openid/AppAuth-Android/issues/289
