### ISSUE TITLE
feat: InApp Browser

### ISSUE THREAD

**Issue by MarkLinovy** [Bdaya-Dev/oidc#79]
**Description**

For Usability Reasons it is recommended to use InApp Browsers where possible. This prevents the user to have to switch applications on certain devices.

Right now the user always sees an unnecessary prompt every time he has to login:

![perm2](https://github.com/Bdaya-Dev/oidc/assets/72862684/5079f248-45db-4b69-90bf-974748eb3a4d)

- Do you plan on including an option for using an InApp Browser?
- I would love to contribute if you would like to see the feature in this package.

> Some platforms support a browser feature known as "in-app browser
   tabs", where an app can present a tab of the browser within the app
   context without switching apps, but still retain key benefits of the
   browser such as a shared authentication state and security context.
   On platforms where they are supported, it is RECOMMENDED, for
   usability reasons, that apps use in-app browser tabs for the
   authorization request.
   
   https://datatracker.ietf.org/doc/html/rfc8252#section-6

**Requirements**

- [ ] InApp Browser

**Comment by ahmednfwela** [comment]
Since we use [AppAuth iOS SDK](https://github.com/openid/AppAuth-iOS), which is made by openid themselves, I don't think there is something for us to do here.

also what you are suggesting is "embedded browser", not in-app browsers which is against spec
https://datatracker.ietf.org/doc/html/rfc8252#section-8.12

**Comment by MarkLinovy** [comment]
Hi and thanks for the feedback. You are right. :)
